### ISSUE TITLE
workout.hasGPSData is not a function

### ISSUE THREAD

**Issue by vbouchet31** [fabulator/endomondo-api-handler#127]
Hi,

I simply copied the script from https://www.npmjs.com/package/endomondo-api-handler#export-your-workouts-to-gpx and it failed with the following error.

TypeError: workout.hasGPSData is not a function
    at /Users/vincent..bouchet/www/endo/test.js:14:23
    at /Users/vincent..bouchet/www/node_modules/endomondo-api-handler/dist/index.js:957:14
    at Array.map (<anonymous>)
    at Api.processWorkouts (/Users/vincent..bouchet/www/node_modules/endomondo-api-handler/dist/index.js:956:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/vincent..bouchet/www/endo/test.js:11:5

I commented the condition and it is working probably because I don't have any workout without GPS data.

**Comment by fabulator** [comment]
Sorry about that, I accidentally removed the method. It's fixed in 3.42.1.
