### ISSUE TITLE
afterDate filter in "search for workouts" example does not exist

### ISSUE THREAD

**Issue by vbouchet31** [fabulator/endomondo-api-handler#128]
Hi,

I tried to filter the workouts which are requested by following the example provided in the README.md. It appears the afterDate filter does not exist but after is the proper filter keyword.

**Comment by vbouchet31** [comment]
It is the first time I do a change straight from github UI so I hope it will work as expected ;-)

**Comment by fabulator** [comment]
Thanks! Merged.
