### ISSUE TITLE
Tcx file from getWorkoutTcx() differs with tcx downloaded from Endomondo

### ISSUE THREAD

**Issue by vbouchet31** [fabulator/endomondo-api-handler#133]
Hi,

I successfully exported all my workouts using the example to download the gpx files:
```
await api.processWorkouts({}, (workout) => {
  console.log(workout.toString());
  if (workout.hasGPSData()) {
    fs.writeFileSync(`tmp/${workout.getId()}.gpx`, workout.toGpx(), 'utf8');
  }
});
```

However, when I tried to import these in my Garmin account, the workouts were uncategorized. Nothing to do with the script, it looks like [an issue](https://forums.garmin.com/apps-software/mobile-apps-web/f/garmin-connect-web/127903/getting-the-activity-type-correct-when-importing-a-gpx) on Garmin side.
I noticed that importing the tcx file properly categorized the workout. I decided to adapt the code to download the files using the getWorkoutTcx() method. Here is my code:
```
await api.processWorkouts({}, (workout) => {
      console.log(workout.toString());

      api.getWorkoutTcx(workout.getId(), workout.getSource().author.id).then(function(tcx) {
          fs.writeFileSync(`tmp/${workout.getId()}.tcx`, tcx, 'utf8');
      }).catch(function(err) {
          console.error(err);
      });
});
```

The script itself works properly but when I tried to import few workouts in my Garmin account, only one is properly imported and the other ones are flagged as duplicate and hence are not imported. For one of these faulty tcx file, I downloaded it manually from Endomondo and compared it with the one I get using the script.
These are identical unless the <Id> attribute. For some reason, all the tcx exported via the script have `<Id>2011-08-02T10:08:02Z</Id>` (even if the workout is actually older than this date).

I have very basic NodeJS knowledge but a brief look at the code shows that getWorkoutTcx() simply does a GET request to https://www.endomondo.com/rest/v1/users/<userId>/workouts/<workoutId>/export?format=TCX which is the same endpoint that is used when downloading from Endomondo UI.
That is confusing ...

**Comment by fabulator** [comment]
I'm unable to reproduce this. I tried to download my 10 last workouts using your code and each tcx file has a different id. Do you use login method to authorize on Endomondo?

**Comment by vbouchet31** [comment]
I am using the login method but given it is the second issue you mentioned you can't reproduce, I am wondering if I am actually using it properly. Given my workouts are public, it may hide the authentication issue. I will try to investigate more on my side. For now, my workaround has been:
```
tcx = tcx.replace('<Id>2011-08-02T10:08:02Z</Id>', `<Id>${year}-${month}-${day}T${hour}:${minute}:00Z</Id>`);
```

**Comment by fabulator** [comment]
I tried to download tcx of two of your workouts. 282212961 and 282209846. I think that ID in tcx does not correspond with a start of workout but time of upload. So if some activities are uploaded in same time, it gets same ID. 

My library just download tcx response from Endomondo and I don't want to process it and replace the id. I will the the note into the README about this problem, so the users can use some regex replace to fix it.

**Comment by vbouchet31** [comment]
What is confusing is that the tcx we get using the library differs from the tcx we get using Endomondo UI. Please see the tcx (I just changed the format given Github does not accept tcx, just replace txt by tcx). In this the ID is `<Id>2014-01-03T17:54:04Z</Id>`
 which matches the time of the workout. If I get the same workout using the library, I get `<Id>2011-08-02T10:08:02Z</Id>`. This workout can't be uploaded in 2011 given I did the workout in 2014.

[20140103_160000.txt](https://github.com/fabulator/endomondo-api-handler/files/4096103/20140103_160000.txt)

I have not checked with many more workouts so I don't know if it is a temporary/old issue with some of my workouts or even the recent ones are impacted. I did extracted all my workouts using the workaround I mentioned and will stop using Endomondo so not really an issue for me.

**Comment by fabulator** [comment]
That is really weird I tried use this code:
```
await api.login(MY_LOGIN, MY_PASSWORD);
const tcx = await api.getWorkoutTcx(282209846, 1863517);
fs.writeFileSync('tmp/a.tcx', tcx, 'utf8');
```
And I got "<Id>2014-01-03T17:52:57Z</Id>". I already put the regex to readme so use can use it to replace Ids in all workouts.
