### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: this.schemaLocation is not iterable

### ISSUE THREAD

**Issue by blazejhanzel** [fabulator/endomondo-api-handler#22]
I get this error when I try to use workout.toGpx() function

`
(node:469) UnhandledPromiseRejectionWarning: TypeError: this.schemaLocation is not iterable
    at new GarminBuilder (/Desktop/node_modules/gpx-builder/dist/index.js:812:13)
    at Workout.toGpx (/Desktop/node_modules/endomondo-api-handler/dist/index.js:853:21)
    at api.processWorkouts (/Desktop/endomondo.js:13:68)
    at workouts.map.workout (/Desktop/node_modules/endomondo-api-handler/dist/index.js:1089:14)
    at Array.map (<anonymous>)
    at Api.processWorkouts (/Desktop/node_modules/endomondo-api-handler/dist/index.js:1088:40)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:469) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:469) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by blazejhanzel** [comment]
Changing line 800 in node_modules/gpx-builder/index.js for this:

`
class GarminBuilder extends BaseBuilder {
  /**
   * Garmin builder include extension for speed, hear rate, cadence, ...
   */
  constructor() {
    super();

    _defineProperty(this, "data", void 0);

    _defineProperty(this, "schemaLocation", void 0);

    this.schemaLocation = ['http://www.garmin.com/xmlschemas/TrackPointExtension/v1', 'http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd', 'http://www.garmin.com/xmlschemas/GpxExtensions/v3', 'http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd'];
    this.data = _objectSpread({}, this.data, {
      attributes: _objectSpread({}, {
        'xmlns:gpxtpx': 'http://www.garmin.com/xmlschemas/TrackPointExtension/v1',
        'xmlns:gpxx': 'http://www.garmin.com/xmlschemas/GpxExtensions/v3'
      })
    });
  }

}
`

looks working. I have some problems with "Invalid time value" but only for few activities so it's not bad :)

**Comment by fabulator** [comment]
I made a mistake in gpx exporting library. I rewrited variables of parent class. It's fixed in v2.0.1
