### ISSUE TITLE
RangeError: Invalid time value when exporting all to GPX

### ISSUE THREAD

**Issue by blazejhanzel** [fabulator/endomondo-api-handler#23]
When I tried to export all activities to gpx (using example from README.md), in some activities I got RangeError because of Invalid time value. I don't know what is the reason of, but I ommit this by adding exception catch in script:

`
            try {
                fs.writeFileSync('tmp/${workout.getId()}.gpx', workout.toGpx(), 'utf8');
            } catch (RangeError) {
                console.error(RangeError);
            }
`

This activities are skipped but their IDs are displayed in terminal and they need to be downloaded manually from Endomondo webiste. (I have about 5% of workouts with this error so it's not too much ;) )

**Comment by fabulator** [comment]
Thanks for reporting :) Is workout you are trying to export public? Or can you send me a json data of workout (https://www.endomondo.com/rest/v1/users/YOUR_USER_ID/workouts/YOUR_WORKOUT_ID) to email michal@fabulator.cz Or there are some details of this error?

**Comment by blazejhanzel** [comment]
I don't have any public workouts, I have only private or shared for friends, so I think it isn't reason. 

Finally, I probably find the reason...
This problem take place when I export workouts with map added manually (not tracked by endomondo, just added later using website).

**Comment by fabulator** [comment]
If you add them manually you mean you are using "Draw route for new workout"? This could result to invalid date because there really is not a DateTime data in those workouts.

**Comment by blazejhanzel** [comment]
Ok, everything is clear now ;)
I suggest to use https://www.endomondo.com/rest/v1/users/USER_ID/workouts/WORKOUT_ID/export?format=GPX there. This converts workout to gpx on the Endomondo server and then download ready gpx file.

**Comment by fabulator** [comment]
I have added getWorkoutGpx method in Api class. I found out that if you get list of points it won't give you such details as downloading gpx file. Thanks.
